import { UnitOfMeasure } from "../enums/UnitOfMeasure";
import { IBaseMaterialCertificate } from "./IBaseMaterialCertificate";
import { IBaseMaterialType } from "./IBaseMaterialType";
import { ICoordinate } from "./ICoordinate";
import { IFillerMaterialCertificate } from "./IFillerMaterialCertificate";
import { IFillerMaterialType } from "./IFillerMaterialType";
import { IIsometric } from "./IIsometric";
import { IJoiner } from "./IJoiner";
import { IJointNdtWithResult } from "./IJointNdtWithResult";
import { INdtReport } from "./INdtReport";
import { IPid } from "./IPid";
import { IPostWeldHeatTreatment } from "./IPostWeldHeatTreatment";
import { IPreheat } from "./IPreheat";
import { IProcessSpecificationProcedure } from "./IProcessSpecificationProcedure";

export interface IJoint {
    id: number;
    number: number;
    coordinatesOnIsometric: ICoordinate;
    pid: IPid;
    isometric: IIsometric;
    sheetOnIsometric: number;
    uom: UnitOfMeasure;
    schedule: string;
    diameter: number;
    fittingDescription1: string;
    baseMaterialType1: IBaseMaterialType;
    baseMaterial1: IBaseMaterialCertificate;
    fittingDescription2: string;
    baseMaterialType2: IBaseMaterialType;
    baseMaterial2: IBaseMaterialCertificate;
    thickness: number;
    fillerMaterialType1: IFillerMaterialType;
    fillerMaterial1: IFillerMaterialCertificate;
    fillerMaterialType2: IFillerMaterialType;
    fillerMaterial2: IFillerMaterialCertificate;
    processSpecificationProcedure: IProcessSpecificationProcedure;
    joiner1: IJoiner;
    joiner2: IJoiner;
    date: Date;
    isFitUpDone: boolean;
    isVisualInspectionDone: boolean;
    ndtReportsWithResults: IJointNdtWithResult[];
    preheat: IPreheat;
    postWeldHeatTreatment: IPostWeldHeatTreatment;
    comments: string;
}